<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Jsoncollection\TransformersJsons\HangUpsTF.json" />
    <None Remove="Jsoncollection\TransformersJsons\InfluencesTF.json" />
    <None Remove="Jsoncollection\TransformersJsons\Origins.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Jsoncollection\TransformersJsons\HangUpsTF.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Jsoncollection\TransformersJsons\InfluencesTF.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Jsoncollection\TransformersJsons\Origins.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="Jsoncollection\TransformersJsons\FocuesesTF.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Jsoncollection\TransformersJsons\GeneralPerksTF.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Jsoncollection\TransformersJsons\Roles.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="SavedCharacters\Transformers\Pdf\" />
    <Folder Include="SavedCharacters\Transformers\Text\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2026.7.1" />
  </ItemGroup>

</Project>
